version: '3.8'

services:
  backend:
    build: .
    container_name: be-abadimurnichicken
    ports:
      - "8080:3000"
    restart: always
    environment:
      - DB_HOST=mysql_container
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=amc-gobackend
      - DB_NAME=db_pos-kds
    networks:
      - mysql_net

networks:
  mysql_net:
    external: true
    name: mysql-service_default